### ISSUE TITLE
ボタン非描画　画面最大化時

### ISSUE THREAD

**Issue by sabamisoyaki** [DAINI-4869/movieClipExtension#1]
## 発生した事象

動画(コンテンツ)内において、画面最大化ボタンを押したときにボタンが表示されない。

## 期待した結果
画面最大化時にも、ボタンが表示される。

## 再現手順

1. Netflix.comへアクセスする
2. 任意の動画(コンテンツ)を再生する
3. 画面最大化ボタンを押す

動画を再生している状態でリロードするとボタンが表示され、一度表示されると左上の矢印で戻り、他の動画を再生してもボタンは表示される。

**Comment by DAINI-4869** [comment]
time-lineではなく、control-volumeを起点に変更することで対応しようと思います。
